redis:
  restart: always
  image: redis:latest
  ports:
    - "6379"

nginx:
  restart: always
  image: nginx:latest
  volumes:
    - ./mysite.template:/etc/nginx/conf.d/mysite.template
  ports:
    - "80"
  environment:
   - NGINX_HOST=198.199.124.91
   - NGINX_PORT=8001
  command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

base:
  dockerfile: Dockerfile
  build: .
  volumes:
    - .:/code

migrate:
  extends:
    service: base
  command: python manage.py migrate

test:
  extends:
    service: base
  command: python manage.py test

run_dev:
  extends:
    service: base
  command: python manage.py runserver 0.0.0.0:8000
  ports:
    - "8000"
  links:
    - redis
    - migrate

run_prod:
  extends:
    service: base
  command: daphne -b 0.0.0.0 -p 8001 djacha.asgi:channel_layer
  ports:
    - "8001"
  links:
    - nginx
    - redis
    - migrate
